### PR TITLE
Add MarkDBConnect for Zotero 7

### LINKED ISSUE #53: Plugin to add
MarkDB-Connect added Zotero 7 compatibility 

https://github.com/daeh/zotero-markdb-connect

### PR DESCRIPTION
**Pull request by northword**
Fixes #53

### CODE REVIEW

**Comment by northword** [comment]
@daeh Hello, I would like to know for what reason you changed the ID of the plugin that is compatible with Zotero7? (Just a question out of curiosity, nothing more)

**Comment by northword** [comment]
> 此插件 z6的id与z7的id不一致

我们改成先前说过的在每一个 `release` 都放一个 id 如何？

**Comment by daeh** [comment]
Hi — only because I used a university email as the ID initially but I won't have that email forever. So I thought I'd change it since I rebuilt the addon from the ground up for zotero 7. It's not too late to revert it back to the original ID, though. Do you think I should change it back?

**Comment by northword** [comment]
> Hi — only because I used a university email as the ID initially but I won't have that email forever. So I thought I'd change it since I rebuilt the addon from the ground up for zotero 7. It's not too late to revert it back to the original ID, though. Do you think I should change it back?

OH, it's up to you. 

From a compatibility aspect, using the same ID and configuring [update.json correctly](https://www.zotero.org/support/dev/zotero_7_for_developers#rdf_manifestjson) will allow the plugin to automatically update to a Zotero 7 compatible version when the user upgrades from Zotero 6 to Zotero 7. Otherwise it requires the user to manually install the plugin once again after updating Zotero. But the reasons you have given are good enough, so just make up your mind.

**Comment by daeh** [comment]
I switched it back. Sorry for the confusion. Everything will be `daeda@mit.edu` from here on and we can forget the other id existed. 

Thanks!

**Pull request merged**
